blank_issues_enabled: true
contact_links:
  - name: WebUI Discussions
    url: https://github.com/maclong9/web-ui/discussions
    about: Please ask questions about usage and implementation here
  - name: Documentation
    url: https://swiftpackageindex.com/maclong9/web-ui/main/documentation/webui
    about: Check the documentation for answers to common questions
  - name: Swift Package Index
    url: https://swiftpackageindex.com/maclong9/web-ui
    about: View the WebUI package on Swift Package Index
