name: Run Tests
on:
  pull_request:
    branches: [main, next]

permissions:
  contents: read

jobs:
  test:
    runs-on: macos-latest
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: "6.1"

      - name: Cache SwiftPM dependencies
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-swiftpm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-swiftpm-

      - name: Resolve dependencies
        run: swift package resolve

      - name: Run tests
        run: swift test
